#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Format code
repoTopLevel=`git rev-parse --show-toplevel`
filesToFormat=""
filesToCommit=""

for file in $(git diff --name-only --cached --diff-filter=ACMRT)
    do
        filesToFormat+="./"$file";"
        filesToCommit+="./"$file" "
    done

echo "🗂  - Files to be formatted:"
echo $filesToFormat

echo "🏎  - Starting formatting..."

dotnet tool restore
dotnet jb cleanupcode --include="$filesToFormat" "weather.sln"

echo "✅ - Formatting complete. Adding changes..."
git add $filesToCommit

# Generate OpenAPI docs
(
  cd $(git rev-parse --show-toplevel)/scripts
  ./generate-openapi-docs.sh
  git add api.yaml
)

exit 0