apiVersion: batch/v1
kind: Job
metadata:
  name: weather-backend
spec:
  template:
    spec:
      containers:
        - name: weather-backend
          image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/weather-backend:latest
      restartPolicy: Never
  backoffLimit: 4