name: "integration-tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integrationTest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Run tests
        run: dotnet test Weather.API.IntegrationTests/Weather.API.IntegrationTests.csproj --configuration Release
