name: .NET

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x
    - name: deploy
      timeout-minutes: 30
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan "$SSH_URL" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        ssh admin@"$SSH_URL" 'rm -rf /home/admin/weather'
        bash ci-scripts/setup_env.sh
        cd ..
        tar czf - weather | ssh admin@$SSH_URL "cd /home/admin && tar xvzf -"
        cd weather
        ssh admin@"$SSH_URL" 'cd /home/admin/weather/weather-backend && sudo docker-compose build'
        ssh admin@"$SSH_URL" 'cd /home/admin/weather/weather-backend && sudo docker-compose down'
        ssh admin@"$SSH_URL" 'cd /home/admin/weather/weather-backend && sudo docker-compose pull'
        ssh admin@"$SSH_URL" 'cd /home/admin/weather/weather-backend && sudo docker-compose up -d'
      env:
        SSH_URL: ${{ secrets.SSH_URL }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        PORT: ${{ secrets.PORT }}
        VIRTUAL_HOST: ${{ secrets.VIRTUAL_HOST }}
        LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
#    - name: Restore dependencies
#      run: |
#        cd weather-backend
#        dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: |
#        cd .. 
#        cd weather-test
#        dotnet test --no-build --verbosity normal
