name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Run Unit Tests
        run: |
          cd weather-test
          dotnet test
      - name: Run Integration Tests
        run: |
          cd Weather.API.IntegrationTests
          dotnet test