name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Unit Tests
        run: |
          cd weather-test
          dotnet test --no-build --verbosity normal
      - name: Integration Tests
        run: |
          cd Weather.API.IntegrationTests
          dotnet test --no-build --verbosity normal
